item {
    id: 1
    name: 'A'
}
item {
    id: 2
    name: 'B'
}
item {
    id: 3
    name: 'C'
}
item {
    id: 4
    name: 'D'
}
item {
    id: 5
    name: 'E'
}
item {
    id: 6
    name: 'F'
}
item {
    id: 7
    name: 'G'
}
item {
    id: 8
    name: 'H'
}
item {
    id: 9
    name: 'I'
}
item {
    id: 10
    name: 'J'
}
item {
    id: 11
    name: 'K'
}
item {
    id: 12
    name: 'L'
}
item {
    id: 13
    name: 'M'
}
item {
    id: 14
    name: 'N'
}
item {
    id: 15
    name: 'O'
}
item {
    id: 16
    name: 'P'
}
item {
    id: 17
    name: 'Q'
}
item {
    id: 18
    name: 'R'
}
item {
    id: 19
    name: 'S'
}
item {
    id: 20
    name: 'T'
}
item {
    id: 21
    name: 'U'
}
item {
    id: 22
    name: 'V'
}
item {
    id: 23
    name: 'W'
}
item {
    id: 24
    name: 'X'
}
item {
    id: 25
    name: 'Y'
}
item {
    id: 26
    name: 'Z'
}
item {
    id: 27
    name: 'a'
}
item {
    id: 28
    name: 'b'
}
item {
    id: 29
    name: 'c'
}
item {
    id: 30
    name: 'd'
}
item {
    id: 31
    name: 'e'
}
item {
    id: 32
    name: 'f'
}
item {
    id: 33
    name: 'g'
}
item {
    id: 34
    name: 'h'
}
item {
    id: 35
    name: 'i'
}
item {
    id: 36
    name: 'j'
}
item {
    id: 37
    name: 'k'
}
item {
    id: 38
    name: 'l'
}
item {
    id: 39
    name: 'm'
}
item {
    id: 40
    name: 'n'
}
item {
    id: 41
    name: 'o'
}
item {
    id: 42
    name: 'p'
}
item {
    id: 43
    name: 'q'
}
item {
    id: 44
    name: 'r'
}
item {
    id: 45
    name: 's'
}
item {
    id: 46
    name: 't'
}
item {
    id: 47
    name: 'u'
}
item {
    id: 48
    name: 'v'
}
item {
    id: 49
    name: 'w'
}
item {
    id: 50
    name: 'x'
}
item {
    id: 51
    name: 'y'
}
item {
    id: 52
    name: 'z'
}
item {
    id: 53
    name: 'qqfstop'
}
item {
    id: 54
    name: 'qqcolon'
}
item {
    id: 55
    name: 'qqhyphen'
}
item {
    id: 56
    name: 'qqbopen'
}
item {
    id: 57
    name: 'qqbclose'
}
item {
    id: 58
    name: 'qqone'
}
item {
    id: 59
    name: 'qqtwo'
}
item {
    id: 60
    name: 'qqthree'
}
item {
    id: 61
    name: 'qqfour'
}
item {
    id: 62
    name: 'qqfive'
}
item {
    id: 63
    name: 'qqsix'
}
item {
    id: 64
    name: 'qqseven'
}
item {
    id: 65
    name: 'qqeight'
}
item {
    id: 66
    name: 'qqnine'
}
item {
    id: 67
    name: 'qqzero'
}
item {
    id: 68
    name: 'qqquestion'
}
item {
    id: 69
    name: 'qqexcalamatory'
}
item {
    id: 70
    name: 'qquscore'
}